HomeWork 01
Raerka/nodejs_mentoring pull request #1
Opened 2018-04-19 11:58 UTC by Raerka

2018-04-19 19:23 UTC, slowpokex requested changes
Almost good, but for 5 stars need to make some changes

2018-04-19 19:23 UTC, slowpokex commented on package.json
> +    "lint": "./node_modules/.bin/eslint ./src",
Just "lint": "eslint ./src" , because you added eslint to devDeps

2018-04-19 19:23 UTC, slowpokex commented on package.json
> +  "babel": {
Maybe need to extract into .babelrc?

2018-04-19 19:23 UTC, slowpokex commented on package.json
> +      "env"
need to add "stage-2"

2018-04-19 19:23 UTC, slowpokex commented on package.json
> +    "babel-node": "babel-node --presets=env",
If you added presets to babel config, the preset flag should be omited

2018-04-19 19:23 UTC, slowpokex commented on package.json
> +    "start": "nodemon --exec npm run babel-node -- src/app.js",
```
"start": "node dist/app.js",
"watch": "nodemon src/index.js --exec babel-node"
```

Did you feel differenses?

2018-04-19 19:23 UTC, slowpokex commented on .eslintrc.js
> +    "rules": {
Please add this rule https://eslint.org/docs/rules/eol-last

2018-04-19 19:23 UTC, slowpokex commented on .gitignore
> +conditions/
please add dist folder ignore

2018-04-20 06:18 UTC, andreikasmykou commented on package.json
> +    "lint": "./node_modules/.bin/eslint ./src",
Fixed, it works. On skype meeting i will need some explanation about this case.

2018-04-20 06:21 UTC, andreikasmykou commented on package.json
> +  "babel": {
Fixed. Is it best practice to extract everything that you can from package.json, e.g. babel settings or jest settings?

2018-04-20 06:37 UTC, Raerka commented on package.json
> +      "env"
Fixed

2018-04-20 06:39 UTC, Raerka commented on package.json
> +    "babel-node": "babel-node --presets=env",
Fixed.

2018-04-20 06:45 UTC, Raerka commented on package.json
> +    "start": "nodemon --exec npm run babel-node -- src/app.js",
Yes.
In first line we run already transpile app.
And in the second we run our app with nodemon which watches any changes in our files and rerun our app.
According to the conditions we needed only two scripts - start and test)))

2018-04-20 06:49 UTC, Raerka commented on .gitignore
> +conditions/
Fixed. dist folder was added.

2018-04-20 06:56 UTC, Raerka commented on .eslintrc.js
> +    "rules": {
Rule was added. Fixed.

2018-04-20 10:55 UTC, slowpokex approved these changes

2018-04-20 10:55 UTC, merged