Hw 02
Raerka/nodejs_mentoring pull request #2
Opened 2018-04-27 14:02 UTC by Raerka

2018-05-01 15:46 UTC, slowpokex requested changes

2018-05-01 15:46 UTC, slowpokex commented on src/app.js
> +const directoryPath = `${__dirname.slice(0, -4)}src\\data`;
path.delimiter instead of \\

2018-05-01 15:46 UTC, slowpokex commented on src/modules/dirwatcher.js
> +    console.log('DirWatcher module'); // eslint-disable-line no-console
This log still needed?

2018-05-01 15:46 UTC, slowpokex commented on src/modules/dirwatcher.js
> +      if (error || !stats.isDirectory()) {
Please separate handling error and !stats.isDirectory expression

2018-05-01 15:46 UTC, slowpokex commented on src/modules/dirwatcher.js
> +      setInterval(() => {
Do you clear this interval?

2018-05-02 05:44 UTC, Raerka commented on src/app.js
> +const directoryPath = `${__dirname.slice(0, -4)}src\\data`;
I think you want to say path.sep
Done

2018-05-02 05:46 UTC, Raerka commented on src/modules/dirwatcher.js
> +    console.log('DirWatcher module'); // eslint-disable-line no-console
No, I think no.
But but and not redundant for now))
Delete.

2018-05-02 06:04 UTC, andreikasmykou commented on src/modules/dirwatcher.js
> +      setInterval(() => {
Add method unWach() and clearTimer in app.js

2018-05-02 06:08 UTC, Raerka commented on src/modules/dirwatcher.js
> +      if (error || !stats.isDirectory()) {
Done

2018-05-05 18:32 UTC, slowpokex approved these changes

2018-05-07 06:13 UTC, merged