Hw 03
Raerka/nodejs_mentoring pull request #3
Opened 2018-05-22 10:53 UTC by Raerka

2018-05-22 15:11 UTC, slowpokex requested changes

2018-05-22 15:11 UTC, slowpokex commented on src/utils/streams.js
> + */
Docs isn't nessessary, but good practice

2018-05-22 15:11 UTC, slowpokex commented on src/utils/streams.js
> +      request(URL, (error, response, body) => {
What about error handling?

2018-05-22 15:11 UTC, slowpokex commented on src/utils/streams.js
> +      request(URL, (error, response, body) => {
And you can make it with pipe
```
request('http://google.com/doodle.png').pipe(fs.createWriteStream('doodle.png'))
```

2018-05-22 15:11 UTC, slowpokex commented on src/utils/streams.js
> +    if (chunk !== null) {
If we have undefined case, what should I see?

2018-05-22 15:11 UTC, slowpokex commented on src/utils/streams.js
> +  }
If we have directory or wrong file?

2018-05-22 15:11 UTC, slowpokex commented on src/utils/streams.js
> +  if (isFile(filePath)) {
Here too

2018-05-22 15:11 UTC, slowpokex commented on src/utils/streams.js
> +  if (isDirectory(directoryPath)) {
Please make another scenario, like if we have a file instead of directory

2018-05-22 15:11 UTC, slowpokex commented on src/utils/streams.js
> +  program.help();
please return false if it not file

2018-05-22 15:11 UTC, slowpokex commented on src/utils/streams.js
> +  program.help();
Here too

2018-05-23 06:04 UTC, Raerka commented on src/utils/streams.js
> + */
Ok)

2018-05-23 06:15 UTC, Raerka commented on src/utils/streams.js
> +      request(URL, (error, response, body) => {
Forgot about error. My fault(
About piping, we need to add data from request to the end file, I tried, but this approach replace all data.

2018-05-23 06:19 UTC, Raerka commented on src/utils/streams.js
> +  }
Refactor a little, now user will see message and help info

2018-05-23 06:19 UTC, Raerka commented on src/utils/streams.js
> +  if (isFile(filePath)) {
Same

2018-05-23 06:28 UTC, Raerka commented on src/utils/streams.js
> +  if (isDirectory(directoryPath)) {
If it is not a directory user will get notification that directoryPath is wrong and help info

2018-05-23 06:29 UTC, Raerka commented on src/utils/streams.js
> +  program.help();
Done

2018-05-23 06:29 UTC, Raerka commented on src/utils/streams.js
> +  program.help();
Done

2018-05-23 06:37 UTC, Raerka commented on src/utils/streams.js
> +    if (chunk !== null) {
Add the same logic as for null

2018-05-23 17:57 UTC, slowpokex approved these changes
Looks good

2018-05-25 22:00 UTC, merged